import frappe
from frappe.custom.doctype.custom_field.custom_field import (
    create_custom_fields as make_custom_fields,
)
from frappe.exceptions import DoesNotExistError
from pharma_vn.setup.taxes import get_vat_rate_options


CUSTOM_FIELDS = {
    "Item": [
        {
            "fieldname": "regulatory_category",
            "label": "Regulatory Category",
            "fieldtype": "Select",
            "options": "\nOTC\nETC\nSupplement\nMedical Device\nCosmeceutical",
            "insert_after": "item_group",
        },
        {
            "fieldname": "drug_registration_no",
            "label": "Drug Registration No",
            "fieldtype": "Data",
            "insert_after": "regulatory_category",
        },
        {
            "fieldname": "storage_condition",
            "label": "Storage Condition",
            "fieldtype": "Data",
            "insert_after": "drug_registration_no",
        },
        {
            "fieldname": "cold_chain_required",
            "label": "Cold Chain Required",
            "fieldtype": "Check",
            "insert_after": "storage_condition",
        },
        {
            "fieldname": "min_remaining_shelf_life_days",
            "label": "Minimum Remaining Shelf Life Days",
            "fieldtype": "Int",
            "insert_after": "cold_chain_required",
        },
        {
            "fieldname": "qa_required",
            "label": "QA Required",
            "fieldtype": "Check",
            "insert_after": "min_remaining_shelf_life_days",
        },
        {
            "fieldname": "pharma_default_sales_vat_rate",
            "label": "Default Sales VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "qa_required",
        },
        {
            "fieldname": "pharma_default_purchase_vat_rate",
            "label": "Default Purchase VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "pharma_default_sales_vat_rate",
        },
    ],
    "Batch": [
        {
            "fieldname": "batch_status",
            "label": "Batch Status",
            "fieldtype": "Select",
            "options": "\nDraft\nQA\nReleased\nHold\nRejected\nRecalled",
            "insert_after": "expiry_date",
        },
        {
            "fieldname": "coa_no",
            "label": "COA No",
            "fieldtype": "Data",
            "insert_after": "batch_status",
        },
        {
            "fieldname": "retest_date",
            "label": "Retest Date",
            "fieldtype": "Date",
            "insert_after": "coa_no",
        },
        {
            "fieldname": "release_date",
            "label": "Release Date",
            "fieldtype": "Datetime",
            "insert_after": "retest_date",
        },
        {
            "fieldname": "released_by",
            "label": "Released By",
            "fieldtype": "Link",
            "options": "User",
            "insert_after": "release_date",
        },
        {
            "fieldname": "temperature_excursion_flag",
            "label": "Temperature Excursion Flag",
            "fieldtype": "Check",
            "insert_after": "released_by",
        },
        {
            "fieldname": "batch_workflow_note",
            "label": "Batch Workflow Note",
            "fieldtype": "Small Text",
            "insert_after": "temperature_excursion_flag",
        },
    ],
    "Customer": [
        {
            "fieldname": "customer_channel",
            "label": "Customer Channel",
            "fieldtype": "Select",
            "options": "\nHospital\nClinic\nPharmacy\nDistributor\nB2C",
            "insert_after": "customer_group",
        },
        {
            "fieldname": "license_no",
            "label": "License No",
            "fieldtype": "Data",
            "insert_after": "customer_channel",
        },
        {
            "fieldname": "license_expiry",
            "label": "License Expiry",
            "fieldtype": "Date",
            "insert_after": "license_no",
        },
        {
            "fieldname": "pharmacist_in_charge",
            "label": "Pharmacist In Charge",
            "fieldtype": "Data",
            "insert_after": "license_expiry",
        },
        {
            "fieldname": "sales_region",
            "label": "Sales Region",
            "fieldtype": "Data",
            "insert_after": "pharmacist_in_charge",
        },
        {
            "fieldname": "credit_review_status",
            "label": "Credit Review Status",
            "fieldtype": "Select",
            "options": "\nPending\nApproved\nBlocked",
            "insert_after": "sales_region",
        },
        {
            "fieldname": "customer_risk_assessment_section",
            "label": "Customer Risk Assessment",
            "fieldtype": "Section Break",
            "insert_after": "credit_review_status",
        },
        {
            "fieldname": "customer_risk_dashboard_html",
            "label": "Risk Dashboard",
            "fieldtype": "HTML",
            "insert_after": "customer_risk_assessment_section",
        },
    ],
    "Supplier": [
        {
            "fieldname": "gmp_certificate_no",
            "label": "GMP Certificate No",
            "fieldtype": "Data",
            "insert_after": "supplier_group",
        },
        {
            "fieldname": "gmp_expiry",
            "label": "GMP Expiry",
            "fieldtype": "Date",
            "insert_after": "gmp_certificate_no",
        },
        {
            "fieldname": "approved_vendor_status",
            "label": "Approved Vendor Status",
            "fieldtype": "Select",
            "options": "\nPending\nApproved\nBlocked",
            "insert_after": "gmp_expiry",
        },
        {
            "fieldname": "supplier_type",
            "label": "Supplier Type",
            "fieldtype": "Select",
            "options": "\nManufacturer\nTrader\nImporter\nService",
            "insert_after": "approved_vendor_status",
        },
    ],
    "Employee": [
        {
            "fieldname": "default_salary_structure",
            "label": "Default Salary Structure",
            "fieldtype": "Link",
            "options": "Salary Structure",
            "insert_after": "company",
        },
    ],
    "Salary Slip": [
        {
            "fieldname": "employee_contract",
            "label": "Employee Contract",
            "fieldtype": "Link",
            "options": "Employee Contract",
            "insert_after": "salary_structure",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_total_working_days",
            "label": "Total Working Days",
            "fieldtype": "Float",
            "insert_after": "employee_contract",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_total_working_hours",
            "label": "Total Working Hours",
            "fieldtype": "Float",
            "insert_after": "pharma_total_working_days",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_overtime_hours",
            "label": "Overtime Hours",
            "fieldtype": "Float",
            "insert_after": "pharma_total_working_hours",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_base_salary",
            "label": "Calculated Base Salary",
            "fieldtype": "Currency",
            "insert_after": "pharma_overtime_hours",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_overtime_salary",
            "label": "Calculated OT Salary",
            "fieldtype": "Currency",
            "insert_after": "pharma_base_salary",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_allowance_total",
            "label": "Allowance Total",
            "fieldtype": "Currency",
            "insert_after": "pharma_overtime_salary",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_deduction_total",
            "label": "Deduction Total",
            "fieldtype": "Currency",
            "insert_after": "pharma_allowance_total",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_taxable_income",
            "label": "Taxable Income",
            "fieldtype": "Currency",
            "insert_after": "pharma_deduction_total",
            "read_only": 1,
        },
        {
            "fieldname": "pharma_payroll_breakdown_json",
            "label": "Payroll Breakdown JSON",
            "fieldtype": "Long Text",
            "insert_after": "pharma_taxable_income",
            "read_only": 1,
        },
    ],
    "Sales Order Item": [
        {
            "fieldname": "required_shelf_life_pct",
            "label": "Required Shelf Life %",
            "fieldtype": "Percent",
            "insert_after": "delivery_date",
        },
        {
            "fieldname": "contract_no",
            "label": "Contract No",
            "fieldtype": "Data",
            "insert_after": "required_shelf_life_pct",
        },
        {
            "fieldname": "promotion_code",
            "label": "Promotion Code",
            "fieldtype": "Data",
            "insert_after": "contract_no",
        },
        {
            "fieldname": "temperature_condition",
            "label": "Temperature Condition",
            "fieldtype": "Data",
            "insert_after": "promotion_code",
        },
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Quotation Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Delivery Note Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Sales Invoice Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Purchase Order Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Purchase Receipt Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Purchase Invoice Item": [
        {
            "fieldname": "pharma_vat_rate",
            "label": "VAT Rate",
            "fieldtype": "Select",
            "options": get_vat_rate_options(),
            "insert_after": "item_tax_template",
            "in_list_view": 1,
        },
    ],
    "Sales Order": [
        {
            "fieldname": "pharma_general_section",
            "label": "Pharma Sales Overview",
            "fieldtype": "Section Break",
            "insert_after": "po_date",
        },
        {
            "fieldname": "pharma_account_name",
            "label": "Account Name",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_general_section",
        },
        {
            "fieldname": "pharma_account_address",
            "label": "Account Address",
            "fieldtype": "Small Text",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_account_name",
        },
        {
            "fieldname": "pharma_general_column_1",
            "fieldtype": "Column Break",
            "insert_after": "pharma_account_address",
        },
        {
            "fieldname": "pharma_contact_name",
            "label": "Contact",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_general_column_1",
        },
        {
            "fieldname": "pharma_contact_phone",
            "label": "Phone",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_contact_name",
        },
        {
            "fieldname": "pharma_contact_email",
            "label": "E-Mail",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_contact_phone",
        },
        {
            "fieldname": "pharma_parties_section",
            "label": "Ship-To / Bill-To",
            "fieldtype": "Section Break",
            "insert_after": "pharma_contact_email",
        },
        {
            "fieldname": "pharma_ship_to_name",
            "label": "Ship-To Name",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_parties_section",
        },
        {
            "fieldname": "pharma_ship_to_address",
            "label": "Ship-To Address",
            "fieldtype": "Small Text",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_ship_to_name",
        },
        {
            "fieldname": "pharma_parties_column_1",
            "fieldtype": "Column Break",
            "insert_after": "pharma_ship_to_address",
        },
        {
            "fieldname": "pharma_bill_to_name",
            "label": "Bill-To Name",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_parties_column_1",
        },
        {
            "fieldname": "pharma_bill_to_address",
            "label": "Bill-To Address",
            "fieldtype": "Small Text",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_bill_to_name",
        },
        {
            "fieldname": "pharma_commercial_section",
            "label": "General",
            "fieldtype": "Section Break",
            "insert_after": "pharma_bill_to_address",
        },
        {
            "fieldname": "pharma_order_description",
            "label": "Description",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_commercial_section",
        },
        {
            "fieldname": "pharma_external_reference",
            "label": "External Reference",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_order_description",
        },
        {
            "fieldname": "pharma_requested_date",
            "label": "Requested Date",
            "fieldtype": "Date",
            "allow_on_submit": 1,
            "insert_after": "pharma_external_reference",
        },
        {
            "fieldname": "pharma_issue_date",
            "label": "Issue Date",
            "fieldtype": "Date",
            "allow_on_submit": 1,
            "insert_after": "pharma_requested_date",
        },
        {
            "fieldname": "pharma_price_basis",
            "label": "Price In",
            "fieldtype": "Select",
            "options": "\nNet\nGross",
            "allow_on_submit": 1,
            "insert_after": "pharma_issue_date",
        },
        {
            "fieldname": "pharma_origin",
            "label": "Origin",
            "fieldtype": "Select",
            "options": "\nManual Entry\nDMS\nCRM\nWebsite\nMobile App\nTender\nEDI",
            "allow_on_submit": 1,
            "insert_after": "pharma_price_basis",
        },
        {
            "fieldname": "pharma_credit_status",
            "label": "Credit Status",
            "fieldtype": "Select",
            "options": "\nNot Checked\nUnder Review\nApproved\nBlocked\nOver Limit",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_origin",
        },
        {
            "fieldname": "pharma_allocation_status",
            "label": "Allocation Status",
            "fieldtype": "Select",
            "options": "\nNot Reserved\nPending Allocation\nPartially Reserved\nFully Reserved",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_credit_status",
        },
        {
            "fieldname": "pharma_send_order_confirmation",
            "label": "Send Order Confirmation",
            "fieldtype": "Check",
            "allow_on_submit": 1,
            "insert_after": "pharma_allocation_status",
        },
        {
            "fieldname": "pharma_commercial_column_1",
            "fieldtype": "Column Break",
            "insert_after": "pharma_send_order_confirmation",
        },
        {
            "fieldname": "pharma_employee_responsible",
            "label": "Employee Responsible",
            "fieldtype": "Link",
            "options": "Employee",
            "allow_on_submit": 1,
            "insert_after": "pharma_commercial_column_1",
        },
        {
            "fieldname": "pharma_sales_unit",
            "label": "Sales Unit",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_employee_responsible",
        },
        {
            "fieldname": "pharma_sales_organization",
            "label": "Sales Organization",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_sales_unit",
        },
        {
            "fieldname": "pharma_distribution_channel",
            "label": "Distribution Channel",
            "fieldtype": "Select",
            "options": "\nHospital\nClinic\nPharmacy\nDistributor\nB2C\nTender",
            "allow_on_submit": 1,
            "insert_after": "pharma_sales_organization",
        },
        {
            "fieldname": "pharma_revenue_contract_id",
            "label": "Revenue Contract ID",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_distribution_channel",
        },
        {
            "fieldname": "pharma_revenue_contract_description",
            "label": "Revenue Contract Description",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_revenue_contract_id",
        },
        {
            "fieldname": "pharma_delivery_section",
            "label": "Delivery",
            "fieldtype": "Section Break",
            "insert_after": "pharma_revenue_contract_description",
        },
        {
            "fieldname": "pharma_delivery_status",
            "label": "Delivery Status",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_delivery_section",
        },
        {
            "fieldname": "pharma_delivery_priority",
            "label": "Delivery Priority",
            "fieldtype": "Select",
            "options": "\nLow\nNormal\nHigh\nUrgent",
            "allow_on_submit": 1,
            "insert_after": "pharma_delivery_status",
        },
        {
            "fieldname": "pharma_complete_delivery",
            "label": "Complete Delivery",
            "fieldtype": "Check",
            "allow_on_submit": 1,
            "insert_after": "pharma_delivery_priority",
        },
        {
            "fieldname": "pharma_delivery_block",
            "label": "Delivery Block",
            "fieldtype": "Select",
            "options": "\nNone\nCredit Block\nWarehouse Hold\nDispatch Hold",
            "allow_on_submit": 1,
            "insert_after": "pharma_complete_delivery",
        },
        {
            "fieldname": "pharma_shipping_condition",
            "label": "Shipping Condition",
            "fieldtype": "Select",
            "options": "\nAmbient\nCold Chain 2-8C\nFrozen\nExpress",
            "allow_on_submit": 1,
            "insert_after": "pharma_delivery_block",
        },
        {
            "fieldname": "pharma_incoterms_location",
            "label": "Incoterms Location",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_shipping_condition",
        },
        {
            "fieldname": "pharma_total_discount_id",
            "label": "Total Discount ID",
            "fieldtype": "Data",
            "allow_on_submit": 1,
            "insert_after": "pharma_incoterms_location",
        },
        {
            "fieldname": "pharma_total_discount_percent",
            "label": "Total Discount %",
            "fieldtype": "Percent",
            "allow_on_submit": 1,
            "insert_after": "pharma_total_discount_id",
        },
        {
            "fieldname": "pharma_total_discount_amount",
            "label": "Total Discount Amount",
            "fieldtype": "Currency",
            "options": "currency",
            "allow_on_submit": 1,
            "insert_after": "pharma_total_discount_percent",
        },
        {
            "fieldname": "pharma_delivery_column_1",
            "fieldtype": "Column Break",
            "insert_after": "pharma_total_discount_amount",
        },
        {
            "fieldname": "pharma_payment_method",
            "label": "Payment Method",
            "fieldtype": "Link",
            "options": "Mode of Payment",
            "allow_on_submit": 1,
            "insert_after": "pharma_delivery_column_1",
        },
        {
            "fieldname": "pharma_payment_reference_type",
            "label": "Payment Reference Type",
            "fieldtype": "Select",
            "options": "\nCustomer PO\nContract\nTransfer Slip\nVirtual Account\nLC",
            "allow_on_submit": 1,
            "insert_after": "pharma_payment_method",
        },
        {
            "fieldname": "pharma_invoice_status",
            "label": "Invoice Status",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_payment_reference_type",
        },
        {
            "fieldname": "pharma_invoice_block",
            "label": "Invoice Block",
            "fieldtype": "Select",
            "options": "\nNone\nHold Invoice\nHold E-Invoice",
            "allow_on_submit": 1,
            "insert_after": "pharma_invoice_status",
        },
        {
            "fieldname": "pharma_approval_status",
            "label": "Approval Status",
            "fieldtype": "Select",
            "options": "\nIn Preparation\nPending Credit Review\nPending Sales Approval\nPending Finance Approval\nApproved\nRejected\nClosed",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_invoice_block",
        },
        {
            "fieldname": "pharma_approval_note",
            "label": "Approval Note",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
            "insert_after": "pharma_approval_status",
        },
        {
            "fieldname": "pharma_notes_section",
            "label": "Notes",
            "fieldtype": "Section Break",
            "insert_after": "pharma_approval_note",
        },
        {
            "fieldname": "pharma_remark_for_supplier",
            "label": "Remark for Supplier",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
            "insert_after": "pharma_notes_section",
        },
        {
            "fieldname": "pharma_customer_information",
            "label": "Customer Information",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
            "insert_after": "pharma_remark_for_supplier",
        },
        {
            "fieldname": "pharma_internal_comment",
            "label": "Internal Comment",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
            "insert_after": "pharma_customer_information",
        },
        {
            "fieldname": "pharma_approval_process_tab",
            "label": "Approval Process",
            "fieldtype": "Tab Break",
            "insert_after": "connections_tab",
        },
        {
            "fieldname": "pharma_workflow_section",
            "label": "Workflow Control",
            "fieldtype": "Section Break",
            "insert_after": "pharma_approval_process_tab",
        },
        {
            "fieldname": "pharma_last_approved_by",
            "label": "Last Approved By",
            "fieldtype": "Link",
            "options": "User",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_workflow_section",
        },
        {
            "fieldname": "pharma_last_approved_on",
            "label": "Last Approved On",
            "fieldtype": "Datetime",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_last_approved_by",
        },
        {
            "fieldname": "pharma_workflow_column_1",
            "fieldtype": "Column Break",
            "insert_after": "pharma_last_approved_on",
        },
        {
            "fieldname": "pharma_rejection_reason",
            "label": "Reason for Rejection",
            "fieldtype": "Small Text",
            "allow_on_submit": 1,
            "insert_after": "pharma_workflow_column_1",
        },
        {
            "fieldname": "pharma_output_history_tab",
            "label": "Output History",
            "fieldtype": "Tab Break",
            "insert_after": "pharma_rejection_reason",
        },
        {
            "fieldname": "pharma_output_section",
            "label": "Order Confirmation",
            "fieldtype": "Section Break",
            "insert_after": "pharma_output_history_tab",
        },
        {
            "fieldname": "pharma_last_confirmation_sent_on",
            "label": "Last Confirmation Sent On",
            "fieldtype": "Datetime",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_output_section",
        },
        {
            "fieldname": "pharma_last_confirmation_sent_to",
            "label": "Last Confirmation Sent To",
            "fieldtype": "Data",
            "read_only": 1,
            "allow_on_submit": 1,
            "insert_after": "pharma_last_confirmation_sent_on",
        },
    ],
    "Purchase Receipt Item": [
        {
            "fieldname": "supplier_batch_no",
            "label": "Supplier Batch No",
            "fieldtype": "Data",
            "insert_after": "batch_no",
            "in_list_view": 1,
            "columns": 2,
        },
        {
            "fieldname": "coa_received",
            "label": "COA Received",
            "fieldtype": "Check",
            "insert_after": "supplier_batch_no",
        },
        {
            "fieldname": "qc_status",
            "label": "QC Status",
            "fieldtype": "Select",
            "options": "\nPending\nPass\nFail",
            "insert_after": "coa_received",
        },
        {
            "fieldname": "wh_layout",
            "label": "WH Layout",
            "fieldtype": "Link",
            "options": "WH Layout",
            "insert_after": "qc_status",
            "in_list_view": 1,
            "columns": 2,
        },
        {
            "fieldname": "wh_cell",
            "label": "WH Cell",
            "fieldtype": "Link",
            "options": "WH Cell",
            "insert_after": "wh_layout",
            "in_list_view": 1,
            "columns": 2,
        },
    ],
    "Delivery Note Item": [
        {
            "fieldname": "wh_layout",
            "label": "WH Layout",
            "fieldtype": "Link",
            "options": "WH Layout",
            "insert_after": "batch_no",
            "in_list_view": 1,
            "columns": 2,
        },
        {
            "fieldname": "wh_cell",
            "label": "WH Cell",
            "fieldtype": "Link",
            "options": "WH Cell",
            "insert_after": "wh_layout",
            "in_list_view": 1,
            "columns": 2,
        },
    ],
    "Sales Invoice": [
        {
            "fieldname": "e_invoice_status",
            "label": "E-Invoice Status",
            "fieldtype": "Select",
            "options": "\nPending\nSubmitted\nIssued\nFailed",
            "insert_after": "naming_series",
        },
        {
            "fieldname": "e_invoice_no",
            "label": "E-Invoice No",
            "fieldtype": "Data",
            "insert_after": "e_invoice_status",
        },
        {
            "fieldname": "payment_gateway_txn_id",
            "label": "Payment Gateway Txn ID",
            "fieldtype": "Data",
            "insert_after": "e_invoice_no",
        },
        {
            "fieldname": "e_invoice_payload_json",
            "label": "E-Invoice Payload JSON",
            "fieldtype": "Long Text",
            "read_only": 1,
            "insert_after": "payment_gateway_txn_id",
        },
        {
            "fieldname": "pharma_compliance_status",
            "label": "Compliance Status",
            "fieldtype": "Data",
            "read_only": 1,
            "insert_after": "e_invoice_payload_json",
        },
        {
            "fieldname": "pharma_compliance_summary",
            "label": "Compliance Summary",
            "fieldtype": "Small Text",
            "read_only": 1,
            "insert_after": "pharma_compliance_status",
        },
        {
            "fieldname": "pharma_invoice_alert_sent",
            "label": "Invoice Alert Sent",
            "fieldtype": "Check",
            "read_only": 1,
            "insert_after": "pharma_compliance_summary",
        },
    ],
}


def create_custom_fields():
    filtered_custom_fields = {}

    for doctype, fields in CUSTOM_FIELDS.items():
        try:
            meta = frappe.get_meta(doctype)
        except DoesNotExistError:
            frappe.logger("pharma_vn").info(
                "Skipping custom fields for %s because the DocType does not exist on this site",
                doctype,
            )
            continue
        filtered_fields = []

        for field in fields:
            fieldname = field["fieldname"]
            if frappe.db.exists("Custom Field", {"dt": doctype, "fieldname": fieldname}):
                filtered_fields.append(field)
                continue

            if meta.get_field(fieldname):
                frappe.logger("pharma_vn").info(
                    "Skipping custom field %s on %s because a standard field already exists",
                    fieldname,
                    doctype,
                )
                continue

            filtered_fields.append(field)

        if filtered_fields:
            filtered_custom_fields[doctype] = filtered_fields

    if filtered_custom_fields:
        make_custom_fields(filtered_custom_fields, update=True)
